name: Evgeny's Borzenin blog
author: Evgeny Borzenin
description: Evgeny's Borzenin blog

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://avatars0.githubusercontent.com/u/155018?s=60&u=a057dc9b607a2f075050b3a027793f6ec2fd4e2b&v=4

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: evgeny.borzenin@gmail.com
  github: evgenyb/iac-meetup
  instagram:
  linkedin: evgeny-borzenin-8b13a4
  rss: rss

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: 

# Google Analytics
google_analytics: UA-156553535-3

# Used for Sitemap.xml and your RSS feed
url: http://borzenin.no
#enforce_ssl: https://borzenin.no

permalink: /:title/

include: ['_pages']

paginate: 6
paginate_path: /page:num/

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

